version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "powerwall-controller"
s3_prefix = "powerwall-controller"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "OnPeakReserve=\"20\" TimeZone=\"America/Phoenix\" Debug=\"*:info\""
