version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "powerwall-controller"
s3_prefix = "powerwall-controller"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TimeZone=\"America/Phoenix\" Debug=\"*:info\""

[default.local_start_api.parameters]
parameter_overrides = "TimeZone=\"America/Phoenix\" Debug=\"*,-follow-redirects\""
docker_network = "lambda-local"
warm_containers = "EAGER"

[default.local_invoke.parameters]
parameter_overrides = "TimeZone=\"America/Phoenix\" Debug=\"*,-follow-redirects\""
docker_network = "lambda-local"